// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package root

import (
	"github.com/google/wire"
	"github.com/henriquemarlon/swapx/configs"
	"github.com/henriquemarlon/swapx/internal/domain"
	"github.com/henriquemarlon/swapx/internal/infra/cartesi"
	"github.com/henriquemarlon/swapx/internal/infra/repository"
)

// Injectors from wire.go:

func NewOrderHandler(db *configs.InMemoryDB) (*cartesi.OrderBookHandler, error) {
	orderRepositoryInMemory := repository.NewOrderRepositoryInMemory(db)
	orderBookHandler := cartesi.NewOrderHandler(orderRepositoryInMemory)
	return orderBookHandler, nil
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(repository.NewOrderRepositoryInMemory, wire.Bind(new(domain.OrderRepository), new(*repository.OrderRepositoryInMemory)))

var setOrderHandler = wire.NewSet(cartesi.NewOrderHandler)
